GET http://localhost:8080/api/persons/6

###
POST http://localhost:8080/api/persons
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"firstName": "Mads", "lastName": "Olsen", "phone":  "23884990"}

###
DELETE http://localhost:8080/api/persons/6

###
PUT http://localhost:8080/api/persons/2
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"firstName": "Mads", "lastName": "Olsen", "phone":  "23884990"}